### ISSUE TITLE
Python Error when doing manual upload

### ISSUE THREAD

**Issue by jmtroywork** [aws-solutions-library-samples/aws-batch-arch-for-protein-folding#14]
Hi Protein Folding team.  After I ran the cloud formation stack per link provided in the readme, I opened a SageMaker JupyterLab session and than ran the instructions to do manual load per instructions also in the read me:

pip install .
python prep_databases.py

But I ran in to errors when running prep_databases.py.  Below are the commands I ran and the messages.  Any ideas how to correct would be appreciated.  Thank you

'''
sh-4.2$ pip install .
Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
Processing /home/ec2-user/SageMaker/batch-protein-folding-code-repo-020240d92caf
  Preparing metadata (setup.py) ... done
Requirement already satisfied: biopython in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from batchfold==1.0.0) (1.81)
Requirement already satisfied: boto3 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from batchfold==1.0.0) (1.26.125)
Requirement already satisfied: datetime in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from batchfold==1.0.0) (5.1)
Requirement already satisfied: requests in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from batchfold==1.0.0) (2.29.0)
Requirement already satisfied: numpy in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from biopython->batchfold==1.0.0) (1.24.3)
Requirement already satisfied: botocore<1.30.0,>=1.29.125 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from boto3->batchfold==1.0.0) (1.29.125)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from boto3->batchfold==1.0.0) (1.0.1)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from boto3->batchfold==1.0.0) (0.6.0)
Requirement already satisfied: zope.interface in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from datetime->batchfold==1.0.0) (6.0)
Requirement already satisfied: pytz in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from datetime->batchfold==1.0.0) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from requests->batchfold==1.0.0) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from requests->batchfold==1.0.0) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from requests->batchfold==1.0.0) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from requests->batchfold==1.0.0) (2022.12.7)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from botocore<1.30.0,>=1.29.125->boto3->batchfold==1.0.0) (2.8.2)
Requirement already satisfied: setuptools in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from zope.interface->datetime->batchfold==1.0.0) (67.7.2)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.30.0,>=1.29.125->boto3->batchfold==1.0.0) (1.16.0)
Building wheels for collected packages: batchfold
  Building wheel for batchfold (setup.py) ... done
  Created wheel for batchfold: filename=batchfold-1.0.0-py3-none-any.whl size=46502 sha256=178c8542048dbe14c55203d66e7a1bec1380a9f7e216e79d0eef6ec56eb0b3c5
  Stored in directory: /home/ec2-user/.cache/pip/wheels/90/f1/90/24f32d31bd570467a365d8dd5c58401fc915894a02a07fbb2b
Successfully built batchfold
Installing collected packages: batchfold
  Attempting uninstall: batchfold
    Found existing installation: batchfold 1.0.0
    Uninstalling batchfold-1.0.0:
      Successfully uninstalled batchfold-1.0.0
Successfully installed batchfold-1.0.0

sh-4.2$ python prep_databases.py 
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/batch-protein-folding-code-repo-020240d92caf/prep_databases.py", line 57, in <module>
    main()
  File "/home/ec2-user/SageMaker/batch-protein-folding-code-repo-020240d92caf/prep_databases.py", line 22, in main
    batch_environment = BatchFoldEnvironment(boto_session = boto_session)
  File "<attrs generated init batchfold.batchfold_environment.BatchFoldEnvironment>", line 10, in __init__
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/batchfold/batchfold_environment.py", line 72, in load_nested_stacks
    return [
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/batchfold/batchfold_environment.py", line 75, in <listcomp>
    if x.get("ResourceType", []) == "AWS::CloudFormation::Stack"
AttributeError: 'list' object has no attribute 'get'
sh-4.2$ 
```

**Comment by brianloyal** [comment]
Ok, I think I fixed it. Can you give it a shot with the newest version of this repo? (1.10.3)
